import com.google.common.io.Resources;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.AxisState;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryTick;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTick;
import org.jfree.chart.axis.TickType;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.axis.ValueTick;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.jfree.text.TextBlock;
import org.jfree.text.TextBlockAnchor;
import org.jfree.ui.RectangleEdge;
import org.jfree.ui.TextAnchor;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static final Color TRANSPARENT = new Color(0f, 0f, 0f, 0f);

    private void drawChart() throws Exception {
        JFreeChart xyLineChart = ChartFactory.createXYLineChart("", "", "",
                createDataset(),
                PlotOrientation.VERTICAL,
                false, false, false);

        BufferedImage image = ImageIO.read(Resources.getResource("thisone.png"));
//        xyLineChart.setBackgroundImage(image);

        XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer();
        renderer.setSeriesPaint(0, Color.BLACK);
        renderer.setSeriesStroke(0, new BasicStroke(2f));
        renderer.setSeriesShapesVisible(0, false);
        renderer.setSeriesItemLabelsVisible(0, false);

        XYPlot xyPlot = xyLineChart.getXYPlot();
        xyPlot.setBackgroundImage(image);
        xyPlot.setBackgroundPaint(TRANSPARENT);
        xyPlot.setRenderer(renderer);

        NumberAxis myAxis = new NumberAxis(xyPlot.getDomainAxis().getLabel()) {

            @SuppressWarnings("unchecked")
            @Override
            public java.util.List refreshTicks(Graphics2D g2, AxisState state,
                                               Rectangle2D dataArea, RectangleEdge edge) {

                java.util.List allTicks = super.refreshTicks(g2, state, dataArea, edge);
                java.util.List myTicks = new ArrayList();

                for (Object tick : allTicks) {
                    NumberTick numberTick = (NumberTick) tick;

                    if (TickType.MAJOR.equals(numberTick.getTickType()) &&
                            (numberTick.getValue() % 5 != 0)) {
                        myTicks.add(new NumberTick(TickType.MINOR, numberTick.getValue(), "",
                                numberTick.getTextAnchor(), numberTick.getRotationAnchor(),
                                numberTick.getAngle()));
                    }

                    myTicks.add(numberTick);
                }
                return myTicks;
            }
        };

        xyPlot.setDomainAxis(myAxis);

        xyPlot.getDomainAxis().setLowerBound(0d);
        xyPlot.getDomainAxis().setUpperBound(24d);

        ChartUtilities.saveChartAsPNG(new File("./file.png"), xyLineChart, 600, 250);

    }

    private XYDataset createDataset() {
        XYSeries serie = new XYSeries("line");
        serie.add(0d, 4d);
        serie.add(10d, 4d);
        serie.add(10d, 2d);
        serie.add(11d, 2d);
        serie.add(11d, 1d);
        serie.add(12d, 1d);
        serie.add(12d, 2d);
//        serie.add(24d, 2d);

        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(serie);

        return dataset;
    }

    public static void main(String[] args) {
        App app = new App();
        try {
            app.drawChart();
        } catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println("DONE");
    }
}
